#!/usr/bin/env node
/**
 * Generates dist/_headers for Cloudflare Pages.
 *
 * The Content-Security-Policy is built *after* the site is compiled, because
 * Astro inlines small hoisted scripts into the HTML. Rather than weaken the
 * policy with `script-src 'unsafe-inline'`, this hashes every inline script in
 * the build and pins those exact hashes — so the shipped scripts run and
 * nothing else does, including anything an attacker manages to inject.
 *
 * Run automatically as part of `npm run build`.
 */

import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync, readdirSync, statSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const dist = join(root, 'dist');

if (!existsSync(dist)) {
	console.error('✗ dist/ not found. Run `astro build` first.');
	process.exit(1);
}

function htmlFiles(dir) {
	const out = [];
	for (const entry of readdirSync(dir)) {
		const full = join(dir, entry);
		if (statSync(full).isDirectory()) out.push(...htmlFiles(full));
		else if (entry.endsWith('.html')) out.push(full);
	}
	return out;
}

/**
 * Collect sha256 hashes of every executable inline script.
 *
 * `application/ld+json` blocks are data, not script: they are never executed
 * and CSP's script-src does not apply to them, so they are skipped.
 */
const hashes = new Set();
const SCRIPT_RE = /<script([^>]*)>([\s\S]*?)<\/script>/gi;

for (const file of htmlFiles(dist)) {
	const html = readFileSync(file, 'utf8');
	let match;
	while ((match = SCRIPT_RE.exec(html)) !== null) {
		const [, attrs, body] = match;
		if (/\ssrc\s*=/i.test(attrs)) continue;
		if (/type\s*=\s*["']application\/ld\+json["']/i.test(attrs)) continue;
		if (body.trim() === '') continue;

		const hash = createHash('sha256').update(body, 'utf8').digest('base64');
		hashes.add(`'sha256-${hash}'`);
	}
}

const scriptHashes = [...hashes].sort().join(' ');

// Third-party origins the site legitimately talks to. Everything else is denied
// by the default-src fallback.
const GTM = 'https://www.googletagmanager.com';
const GA = 'https://www.google-analytics.com https://analytics.google.com';
const CF_INSIGHTS = 'https://static.cloudflareinsights.com';
const CF_INSIGHTS_API = 'https://cloudflareinsights.com';
const TURNSTILE = 'https://challenges.cloudflare.com';

const csp = [
	`default-src 'self'`,
	`base-uri 'self'`,
	`object-src 'none'`,
	`frame-ancestors 'none'`,
	// Both site forms now post same-origin to Pages Functions, so the email
	// provider's domain no longer needs to be allowed here. The one exception is
	// the 404 page's search box, which submits to Google.
	`form-action 'self' https://www.google.com`,
	`script-src 'self' ${scriptHashes} ${GTM} ${CF_INSIGHTS} ${TURNSTILE}`,
	// Astro emits a small number of inline style attributes; styles cannot
	// execute, so this is a far lower-risk allowance than inline script.
	`style-src 'self' 'unsafe-inline'`,
	`img-src 'self' data: ${GA}`,
	`font-src 'self'`,
	`connect-src 'self' ${GA} ${CF_INSIGHTS_API}`,
	`frame-src ${TURNSTILE}`,
	`manifest-src 'self'`,
	`upgrade-insecure-requests`,
].join('; ');

const headers = `# Generated by scripts/generate-headers.mjs — do not edit by hand.
# Regenerate with \`npm run build\`.
#
# CSP script-src pins the sha256 of every inline script Astro emitted in this
# build, so the policy stays strict without 'unsafe-inline'.

/*
  Content-Security-Policy: ${csp}
  Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
  X-Content-Type-Options: nosniff
  X-Frame-Options: DENY
  Referrer-Policy: strict-origin-when-cross-origin
  Permissions-Policy: geolocation=(), microphone=(), camera=(), payment=(), usb=(), interest-cohort=()
  Cross-Origin-Opener-Policy: same-origin
  Cross-Origin-Resource-Policy: same-origin
  X-Robots-Tag: index, follow

# Conversion destination — never indexed, never cached.
/thank-you/*
  X-Robots-Tag: noindex, follow
  Cache-Control: no-store

# Fingerprinted build assets are safe to cache forever.
/_astro/*
  Cache-Control: public, max-age=31536000, immutable

# Generated social images are content-addressed by page and rarely change.
/og/*
  Cache-Control: public, max-age=31536000, immutable
  X-Robots-Tag: noindex

/images/*
  Cache-Control: public, max-age=604800

# The lead magnet. Cached for a day so a regenerated kit propagates quickly.
/downloads/*
  Cache-Control: public, max-age=86400
  X-Robots-Tag: noindex

# The feed should revalidate so new posts appear promptly in readers.
/rss.xml
  Cache-Control: public, max-age=0, must-revalidate
  Content-Type: application/rss+xml; charset=utf-8

# HTML should always revalidate so content edits go live immediately.
/*.html
  Cache-Control: public, max-age=0, must-revalidate
`;

writeFileSync(join(dist, '_headers'), headers);

console.log(
	`✓ Wrote dist/_headers with CSP pinning ${hashes.size} inline script hash(es).`,
);
